Repository Apurvgeek/programs-in-python, pull requests merged in 2021-10, with the labels that each got.

#1 Binary Search in py
  Binary Search Py.py
Labels: hactoberfest

#3 Added heap sort
  heap_sort.py
Labels: hactoberfest-accepted

#5 Create BubbleSort.py
  BubbleSort.py
Labels: hactoberfest-accepted

#7 find haming number
  haming number.py
Labels: hactoberfest-accepted

#10 Create Tower of Hanoi
  Tower of Hanoi
Labels: hactoberfest-accepted

#12 Create Max Heap in Python
  Max Heap in Python
Labels: hactoberfest-accepted

#13 Add files via upload
  facefinal.py
Labels: hactoberfest-accepted

#4 Snake Game in python
  Snake Game.py
Labels: hacktoberfest-accepted

#9 Added calculator.py file
  calculator.py
Labels: hacktoberfest-accepted

#24 Create text_to_speech.py
  text_to_speech.py
Labels: hacktoberfest-accepted

#23 ENCODER DECODER
  encoderdecoder.py
Labels: hacktoberfest-accepted

#51 Create Stack implementation
  Stack implementation
Labels: hacktoberfest-accepted

#54 Create insertions in linked_list
  insertions in linked_list
Labels: hacktoberfest-accepted

#53 Create traversal of linked list
  traversal of linked list
Labels: hacktoberfest-accepted

#52 Create queue implementation
  queue implementation
Labels: hacktoberfest-accepted
